
const TURNSTILE_DEV_MANAGED_KEY = "0x4AAAAAAAEK5ipDQf08Grp5";
const TURNSTILE_PROD_MANAGED_KEY = "0x4AAAAAAAD8PZ3KL9PeONIv";
export const TURNSTILE_MANAGED_KEY = process.env.NODE_ENV === "development" ? TURNSTILE_DEV_MANAGED_KEY : TURNSTILE_PROD_MANAGED_KEY;
