query ExpensesGet($getData: ExpensesGetInput!)
{
    expensesGet(expenseGetData: $getData)
    {
        expenses {
            id
            date 
            price
            currency
        }

        error {
            name
            field
        }
    }
}