
query UserGet
{
    userGet
    {
        user {
            lastname
            firstname
            preferred_currency
            verified_email
        }

        error {
            name
        }
    }
}
