
query UserGet
{
    userGet
    {
        user {
            lastname
            firstname
            email
            preferred_currency
            verified_email
            plan
        }

        error {
            name
        }
    }
}
